### ISSUE TITLE
Pages sending cookies are being cached leading to other users getting logged in

### ISSUE THREAD

**Issue by MartijnHols** [CachetHQ/Docker#272]
I noticed this when I opened my status page in incognito while I was already logged in, and verified it worked by opening the status page on another server and getting logged in without ever entering any credentials. This basically means that **anyone can get full access to your dashboard by simply visiting the status page** given that it cached the logged in user's page.

I verified this with CloudFlare in front of it, with CF disabled and through direct IP access. I am running the Docker container with recommended settings except I am using MariaDB instead of PostgreSQL.

Steps to reproduce:
1. Login to your dashboard
2. Wait a minute or two so the status page's cache expires
3. Open the status page, if you see the edit/delete buttons on incidents that means it sees you as logged in (if these buttons don't appear it will have cached the logged out version you opened prior to logging in, this will also overwrite your cookies, logging you out)
4. Now open the status page in another browser, incognito, or on another device
5. You're logged in there and can do **everything**

This seems like a pretty serious security issue.

How I start my containers:

```jsx
docker run -d --name database --restart unless-stopped -e MYSQL_ROOT_PASSWORD=my-secret-pw -e MYSQL_DATABASE=cachet mariadb:10.3.2
docker run -d --name cachet --restart unless-stopped --link database -p 80:8000 -e DB_DRIVER=mysql -e DB_HOST=database -e DB_DATABASE=cachet -e DB_USERNAME=root -e DB_PASSWORD=my-secret-pw -e APP_KEY=base64:my-secret-app-key -e CACHE_DRIVER=apc -e SESSION_DRIVER=apc -e QUEUE_DRIVER=database -e MAIL_DRIVER=mailgun -e MAIL_HOST=smtp.mailgun.org -e MAIL_PORT=587 -e MAIL_USERNAME=mg.wowanalyzer.com -e MAIL_PASSWORD=my-secret-key -e MAIL_ADDRESS=noreply@mg.wowanalyzer.com -e MAIL_NAME="WoWAnalyzer.com" -e MAIL_ENCRYPTION=tls cachethq/docker:2.3.13
```

**Comment by djdefi** [comment]
Hmm that is not good. I think I must have introduced this when I changed `SESSION_DRIVER` default to `cookie` -- I guess we need to use a better default there, or at least figure out why the sessions are getting shared. 

@CachetHQ/core what do you recommend for `SESSION_DRIVER` ? `file` ?

**Comment by tuxity** [comment]
I have exactly the same problem, sometimes my team members are logged with my session.

**Comment by adamrpridham** [comment]
We are having this issue as well. Unfortunately we are just starting to use the product, and it is kind of a dealbreaker for us.

Not a programmer but if anyone needs assistance reproducing or getting logs, I am happy to help.

**Comment by adamrpridham** [comment]
@tuxity -> How are you updating this in docker? I tried updating session.php to read as file, and restarting the container, but still experiencing the issue.

**Comment by tuxity** [comment]
@adamrpridham When running my container I put `-e SESSION_DRIVER=file` to do the overwrite. I still don't have issue for now, or my team didn't reported it :D

**Comment by adamrpridham** [comment]
@tuxity @djdefi I'm not quite sure this is resolved -> I am using docker compose, and I 

1. Set the session driver environment variable to file, 
2. created a new cachet instance, 

I am still able to reliably reproduce the issue. I worked around it by adding this custom CSS:
.panel-heading {
    visibility: hidden;
}

This hides the buttons that a user would click to edit the page. You can still log into the admin interface if you know the URL, but at least it won't be obvious to those who don't know the URL.

**Comment by adamrpridham** [comment]
Slight update -> I changed the CSS to hide just the buttons instead of the entire panel heading:

div.pull-right.btn-group {
    visibility: hidden;
}

**Comment by djdefi** [comment]
@adamrpridham can you try setting `apc` as the driver instead of file? I think that is what the core team recommends currently.

**Comment by adamrpridham** [comment]
@djdefi We're giving that a shot and I will post an update when available!

**Comment by MartijnHols** [comment]
Still experiencing this issue, even when using the file session driver. For now I've opted not to open the dashboard after logging in.

**Comment by djdefi** [comment]
@MartijnHols how about with `apc` ?

**Comment by MartijnHols** [comment]
As shown in the environment variables in the original post that's what I started with.

**Comment by adamrpridham** [comment]
Can confirm it is still an issue for me. I am using APC now and it's still occurring.

**Comment by djdefi** [comment]
Can you try building from master or again from the the v2.3.13 tag, or pull from the Docker hub: `cachethq/docker:2.3.13` or `cachethq/docker:latest` ?

I am unable to reproduce this using those tags.

**Comment by jwashington104** [comment]
Any update this is still quite proliferant and is preventing my company from using it. I have a feeling it's due to the underlying NGINX config.

**Comment by jwashington104** [comment]
This is still going on, I think this may be down to the underlying Nginx config.

**Comment by jbrooksuk** [comment]
This looks more like it. Cachet itself wouldn’t be sharing sessions.

**Comment by jwashington104** [comment]
Is there a way I can get my changes into the repo? I feel that the rest of the community will want to be able to use it.

**Comment by djdefi** [comment]
@jwashington104 feel free to submit a pull request! 

- https://help.github.com/categories/collaborating-with-issues-and-pull-requests/
